### ISSUE TITLE
(Version) App dies when click "Config" on Android 6.0.1

### ISSUE THREAD

**Issue by soowon-kang** [woohyeok-choi/ABC-Logger#25] opened 2020-02-08 09:00 UTC
**Describe the bug**

The app crash occurs when click Config button.

**To Reproduce**

**Expected behavior**

**Screenshots**

![1581129974916](https://user-images.githubusercontent.com/8052474/74082397-cc3b1880-4a9c-11ea-893f-d33e31dc6260.jpg)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

Android 6.0.1 and GalaxyS5

**Additional context**

**Comment by woohyeok-choi** [comment] 2020-02-09 01:43
I found that this problem only occurs on Android 6.0.1. This may be due to incomplete compilation of Kotlin code, especially a static function (companion object in Kotlin).  

The putting annotation, @JvmStatic, in the static functions may be resolve this problem (but I'm not sure). BTW, users of Android 6.0.1 should be excluded till I definitely resolve the problem.

**Comment by woohyeok-choi** [comment] 2020-02-10 00:44
Alternatives for resolving this problem is to change Kotlin's object into a class, and use this class as a singleton class. I guess this option does not need additional test for reproduction :) but it requires some time for implementation.

**Closed as completed** 2020-10-20 02:53 UTC
Labels: bug, help wanted
